import{createContext,useContext,useEffect,useState}from"react";import{questions as seedQuestions,papers as seedPapers,exams as seedExams}from"../utils/mockData";
const C=createContext(null);
const read=(k,f)=>{try{const v=JSON.parse(localStorage.getItem(k));return v??f}catch{return f}};
export function DataProvider({children}){const[questions,setQuestions]=useState(()=>read("qf_questions",seedQuestions));const[papers,setPapers]=useState(()=>read("qf_papers",seedPapers));const[exams,setExams]=useState(()=>read("qf_exams",seedExams));const[results,setResults]=useState(()=>read("qf_results",[]));
useEffect(()=>localStorage.setItem("qf_questions",JSON.stringify(questions)),[questions]);useEffect(()=>localStorage.setItem("qf_papers",JSON.stringify(papers)),[papers]);useEffect(()=>localStorage.setItem("qf_exams",JSON.stringify(exams)),[exams]);useEffect(()=>localStorage.setItem("qf_results",JSON.stringify(results)),[results]);
const addQuestions=items=>setQuestions(q=>[...q,...items.map((x,i)=>({...x,id:Date.now()+i}))]);
const addPaper=cfg=>{const id="p-"+Date.now();const selected=questions.filter(q=>cfg.subject==="Mixed"||q.subject===cfg.subject).slice(0,Number(cfg.count)||10);const paper={id,name:cfg.name,questions:selected.length,duration:Number(cfg.duration)||60,status:"Draft",modes:["Online","Paper"],questionIds:selected.map(q=>q.id),subject:cfg.subject};setPapers(p=>[paper,...p]);setExams(e=>[{...paper,examId:"exam-"+Date.now(),students:0,marks:selected.length*4},...e]);return paper};
const addResult=result=>setResults(r=>[result,...r]);const resetData=()=>{setQuestions(seedQuestions);setPapers(seedPapers);setExams(seedExams);setResults([])};
return <C.Provider value={{questions,papers,exams,results,addQuestions,addPaper,addResult,resetData}}>{children}</C.Provider>}
export const useData=()=>useContext(C);